### PR TITLE
fix CI on github

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This PR should fix the CI build failures by moving to a supported nodejs version. E.g. from 12 to 20.

There was no fixture for `keepOnlyDuplicateLines` so the test was failing. It succeeds now on my machine (linux).

```json
      {
	"command": "sortLines.keepOnlyDuplicateLines",
	"title": "Sort lines (keep only duplicated lines)"
      },
```

See the runs on https://github.com/dotnetCarpenter/vscode-sort-lines/actions

### CODE REVIEW

**Review by Tyriar — COMMENTED** [review]
Thanks a lot for this, looks like it's working well! Did you have any more changes coming or is this ready to review?

**Comment by dotnetCarpenter** [comment]
You're welcome @Tyriar. It's ready for review.

I have two minor grievances with this PR.

1.   [GabrielBB/xvfb-action@v1](https://github.com/GabrielBB/xvfb-action/) is used, that sets [node to version 12](https://github.com/GabrielBB/xvfb-action/blob/master/action.yml#L17), which gives a warning "The following actions uses node12 which is deprecated and will be forced to run on node16: GabrielBB/xvfb-action@v1. I'm hesitant to switch to the successor [coactions/setup-xvfb](https://github.com/coactions/setup-xvfb) since its CI is failing. I could not find an alternative and considered simply using `xvfb-run` on `ubuntu-latest`.
2. I don't have a way to test _release.yml_ but updated the node version anyway. Perhaps I should had also updated it to use the cache mechanism provided by `actions/setup-node@v4` and updated `actions/checkout` to 4, as in _ci.yml_. But I'm hesitant to make any changes to something I can not test.

If you are happy to merge it with these two deficits or happy to fix them yourself - it's ready for merge :partying_face: 

I would not mind adding a commit for `xvfb-run` on `ubuntu-latest` to get rid of GabrielBB/xvfb-action if you think it's a good idea.

**Comment by dotnetCarpenter** [comment]
Actually, my Windows workaround is not needed. I'll remove that commit and force push.

Upgrading to the newest @vscode/test-electron was enough. I didn't spot it because the Windows runner was cancelled due to lint errors in the linux runner.

**Comment by dotnetCarpenter** [comment]
ready for review

**Comment by Tyriar** [comment]
> [GabrielBB/xvfb-action@v1](https://github.com/GabrielBB/xvfb-action/) is used, that sets [node to version 12](https://github.com/GabrielBB/xvfb-action/blob/master/action.yml#L17), which gives a warning "The following actions uses node12 which is deprecated and will be forced to run on node16: GabrielBB/xvfb-action@v1." I'm hesitant to switch to the successor [coactions/setup-xvfb](https://github.com/coactions/setup-xvfb) since its CI is failing. I could not find an alternative and considered simply using xvfb-run on ubuntu-latest.

I see it used to be 1.2 and downgraded to1 1, was that necessary? We could do what VS Code does instead of using an action also: https://github.com/microsoft/vscode/blob/c48f21c72c02bfe127a65015406dbf02532eb0e6/.github/workflows/basic.yml#L24-L30

Removing any node 12 use is a win if you think it's easy to fix. Good thing for a separate PR though as this one is a decent size already.

**Comment by dotnetCarpenter** [comment]
> > [GabrielBB/xvfb-action@v1](https://github.com/GabrielBB/xvfb-action/) is used, that sets [node to version 12](https://github.com/GabrielBB/xvfb-action/blob/master/action.yml#L17), which gives a warning "The following actions uses node12 which is deprecated and will be forced to run on node16: GabrielBB/xvfb-action@v1." I'm hesitant to switch to the successor [coactions/setup-xvfb](https://github.com/coactions/setup-xvfb) since its CI is failing. I could not find an alternative and considered simply using xvfb-run on ubuntu-latest.
> 
> I see it used to be 1.2 and downgraded to1 1, was that necessary? 

It's my understanding that `@1` will pick the highest 1.x version, so it was suppose to pick 1.4 over 1.2. But I might be wrong.

>We could do what VS Code does instead of using an action also: https://github.com/microsoft/vscode/blob/c48f21c72c02bfe127a65015406dbf02532eb0e6/.github/workflows/basic.yml#L24-L30

I think it would even easier to use [`xvfb-run -a yarn test`](https://github.com/microsoft/vscode-test/blob/main/sample/.github/workflows/ci.yml#L30)

```yaml
- name: Run tests
run: xvfb-run -a yarn test
if: runner.os == 'Linux'
```

```
xvfb-run --help
Usage: xvfb-run [OPTION ...] COMMAND
Run COMMAND (usually an X client) in a virtual X server environment.
Options:
-a        --auto-servernum          try to get a free server number, starting at
                                    --server-num

```

**Pull request merged**
