### PR TITLE
Resolved Issue #5

### PR DESCRIPTION
**Pull request by SoftwareApe**
I looked at this issue #5 which was also bothering me a little bit sometimes. I changed one of the test files to also contain empty lines to remove (spaces, mixed tabs and spaces and empty).

### CODE REVIEW

**Comment by SoftwareApe** [comment]
The linter failed at wrong use of quotation marks. Changed in new commit.

**Comment by SoftwareApe** [comment]
I made the setting configurable as requested. I couldn't figure out how to switch the setting properly on and off without messing with user settings for the unit tests, so I now reverted the test cases to the old state. If you have an idea how to add test cases for this feature I think that might be good.

**Comment by SoftwareApe** [comment]
BTW I named it sortLines.filterBlankLines, because it doesn't filter only empty lines, but also pure white space lines (tabs/spaces/mixed).

**Comment by Tyriar** [comment]
Published v1.7.0

**Pull request merged**
