### PR TITLE
Deps

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
This PR builds upon #145.  But adds a few things more:

+ Remove yarn and use `npm` instead.
+ Updates all dependencies.
+ Switch from deprecated tslint to eslint - thereby there is no need for `tslint.json` (replaced by `eslint.config.mjs`).
+ By switching to eslint, glob is only included once as version 8 (de-duped).
    + tslint-consistent-codestyle required glob@7 and tslint-consistent-codestyle seems [abandon](https://github.com/ajafff/tslint-consistent-codestyle/pull/148)
+ `xvfb.init` is removed and has been irrelevant since at least #146.

EDIT: I'm marking this ready for review @Tyriar because it's ready.

### CODE REVIEW

**Review by 786maan — COMMENTED** [review]
yarn.lock

**Comment by dotnetCarpenter** [comment]
@786maan `yarn.lock` is deleted and replaced by `package-lock.json` because @Tyriar said, in https://github.com/Tyriar/vscode-sort-lines/pull/145#issuecomment-2466246964, that he wants to remove yarn to simplify things even more.

>Another clean up I'd like to do FYI is to remove yarn to simplify things even more.

**Comment by dotnetCarpenter** [comment]
@Tyriar I force pushed to sign all my commits with my signature (I was on a different PC, when I made the PR).

**Comment by dotnetCarpenter** [comment]
Last commit [2b2238f](https://github.com/Tyriar/vscode-sort-lines/pull/147/commits/2b2238f5366b8b675cf9bbad434759acc7ad9695), means:

```
$ npm ls cross-spawn
sort-lines@1.12.0
├─┬ eslint@9.15.0
│ └── cross-spawn@7.0.6
└─┬ webpack-cli@5.1.4
  └── cross-spawn@7.0.6 deduped
```

**Review by Tyriar — APPROVED** [review]
Thanks! 👏

**Pull request merged**
