### PR TITLE
fix release Continues Delivery

### PR DESCRIPTION
**Pull request by dotnetCarpenter**
- update checkout action
- use checkout cache instead of cache action
- get rid of npm usage

### CODE REVIEW

**Comment by dotnetCarpenter** [comment]
I don't understand the failure point: `- Resolving version...`

```
Run GabrielBB/xvfb-action@v1
  with:
    run: yarn test
/Users/runner/.yarn/bin/yarn test
yarn run v1.22.22
warning sort-lines@1.12.0: The engine "vscode" appears to be invalid.
$ yarn compile
warning sort-lines@1.12.0: The engine "vscode" appears to be invalid.
$ tsc -p ./
$ node ./out/test/runTest.js
- Resolving version...
Failed to run tests
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: The process '/Users/runner/.yarn/bin/yarn' failed with exit code 1
```

**Comment by dotnetCarpenter** [comment]
I'm marking this as draft until #146 is merged. It seems that GabrielBB/xvfb-action@v1 is flaky on macos.
This PR passes all checks after #146. See https://github.com/dotnetCarpenter/vscode-sort-lines/actions/runs/11749950666

**Comment by Tyriar** [comment]
> get rid of npm usage

Another clean up I'd like to do FYI is to remove yarn to simplify things even more. VS Code's codebase moves away from this some time ago and that's the main reason some of my projects were on it to keep things consistent.

**Comment by dotnetCarpenter** [comment]
> > get rid of npm usage
> 
> Another clean up I'd like to do FYI is to remove yarn to simplify things even more. 

So move to npm?

**Comment by dotnetCarpenter** [comment]
Surpassed by #147

**Pull request closed without merging**
